### ISSUE TITLE
[bug] crashes when reopen editor with unsaved file

### ISSUE THREAD

**Issue by Ovilia** [Saul-Mirone/milkdown-vscode#12] opened 2021-09-25 09:21 UTC
Steps to reproduce:

1. Open a new file but don't save it
2. Type something
3. Right-click the tab of the file, choose "重新打开编辑器的方式" (Maybe "Reopen the editor with"? in the English version?)

<img width="473" alt="截屏2021-09-25 下午3 44 59" src="https://user-images.githubusercontent.com/779050/134766468-b8f49172-ac84-4587-951d-bc11e1c5f0df.png">

The file crashes and the previous content is gone. Forever! :(

I can help to debug if someone gives me a hint on how to do this. No experience with VSCode extensions. Thanks!

**Comment by Saul-Mirone** [comment] 2021-09-25 15:12
Let me have a look on this

**Comment by Saul-Mirone** [comment] 2021-09-27 13:02
I tried a lot of ways but I cannot reproduce, what's your vscode version?

**Comment by Saul-Mirone** [comment] 2021-10-04 06:18
Should be fixed in v0.0.10, feel free to reopen if you have further questions.

**Closed by Saul-Mirone** 2021-10-04 06:18 UTC
Labels: bug
